import type { KnowledgeBase, KnowledgeBaseV2 } from '@/lib/types'
import { calculateDepth, computeProgress, calculateDepthV2, computeProgressV2 } from '@/lib/ai/depth'

// ─── Safe KB V2 accessor ──────────────────────────────────────────────────────
// Ensures all nested fields exist before any function accesses them.
// Prevents crashes when KB is partially migrated or malformed.

function safe(kb: KnowledgeBaseV2): KnowledgeBaseV2 {
  return {
    business: {
      problem: kb?.business?.problem ?? '',
      objectives: kb?.business?.objectives ?? [],
      success_metrics: kb?.business?.success_metrics ?? [],
      stakeholders: kb?.business?.stakeholders ?? [],
    },
    actors: kb?.actors ?? [],
    use_cases: {
      normal: kb?.use_cases?.normal ?? [],
      edge: kb?.use_cases?.edge ?? [],
    },
    process_flow: kb?.process_flow ?? [],
    functional_requirements: kb?.functional_requirements ?? [],
    business_rules: kb?.business_rules ?? [],
    data_model: {
      entities: kb?.data_model?.entities ?? [],
      relationships: kb?.data_model?.relationships ?? [],
    },
    system_design: {
      architecture: {
        frontend: kb?.system_design?.architecture?.frontend ?? '',
        backend: kb?.system_design?.architecture?.backend ?? '',
        database: kb?.system_design?.architecture?.database ?? '',
        ai_layer: kb?.system_design?.architecture?.ai_layer ?? '',
      },
      api_endpoints: kb?.system_design?.api_endpoints ?? [],
    },
    ux: {
      user_flow: kb?.ux?.user_flow ?? [],
      screens: kb?.ux?.screens ?? [],
    },
    completion: {
      score: kb?.completion?.score ?? 0,
      depth: kb?.completion?.depth ?? 0,
      prompt_version: kb?.completion?.prompt_version ?? 2,
    },
  }
}

// ─── BPMN 2.0 XML ─────────────────────────────────────────────────────────────

export function generateBPMNXml(kb: KnowledgeBase): string {
  const steps = kb.process_flow
  const decisions = kb.decision_points

  if (steps.length === 0) return ''

  const processId = `Process_${steps[0].replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '').slice(0, 20) || '1'}`

  let xml = `<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
             xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
             xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
             xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
             targetNamespace="http://bpmn.io/schema/bpmn">
  <process id="${processId}" isExecutable="false">
    <startEvent id="StartEvent_1" name="Start" />
`

  steps.forEach((step, i) => {
    xml += `    <userTask id="Task_${i}" name="${escapeXml(step)}" />\n`
  })

  decisions.forEach((decision, i) => {
    xml += `    <exclusiveGateway id="Gateway_${i}" name="${escapeXml(decision)}" />\n`
  })

  xml += `    <endEvent id="EndEvent_1" name="End" />\n`

  // Sequence flows
  xml += `    <sequenceFlow id="Flow_start" sourceRef="StartEvent_1" targetRef="Task_0" />\n`
  for (let i = 0; i < steps.length - 1; i++) {
    xml += `    <sequenceFlow id="Flow_${i}" sourceRef="Task_${i}" targetRef="Task_${i + 1}" />\n`
  }
  xml += `    <sequenceFlow id="Flow_end" sourceRef="Task_${steps.length - 1}" targetRef="EndEvent_1" />\n`

  xml += `  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="${processId}" />
  </bpmndi:BPMNDiagram>
</definitions>`

  return xml
}

// ─── Mermaid flowchart ────────────────────────────────────────────────────────

export function generateMermaid(kb: KnowledgeBase): string {
  const steps = kb.process_flow
  const decisions = kb.decision_points

  if (steps.length === 0) return ''

  let diagram = 'flowchart TD\n'
  diagram += '  Start([▶ Start])\n'

  steps.forEach((step, i) => {
    const label = step.length > 40 ? step.substring(0, 40) + '…' : step
    diagram += `  Step${i + 1}["${escapeMermaid(label)}"]\n`
  })

  decisions.forEach((d, i) => {
    const label = d.length > 35 ? d.substring(0, 35) + '…' : d
    diagram += `  Dec${i + 1}{"${escapeMermaid(label)}"}\n`
  })

  diagram += '  End([■ End])\n'
  diagram += '  Start --> Step1\n'
  for (let i = 0; i < steps.length - 1; i++) {
    diagram += `  Step${i + 1} --> Step${i + 2}\n`
  }
  diagram += `  Step${steps.length} --> End\n`

  decisions.forEach((_, i) => {
    if (i < steps.length) {
      diagram += `  Step${i + 1} -.->|decision| Dec${i + 1}\n`
    }
  })

  return diagram
}

// ─── Unified System Document (BRD + SRS) ─────────────────────────────────────

export function generateUSD(kb: KnowledgeBase, projectName: string): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  const depthScore = calculateDepth(kb)
  const completionPct = Math.round(computeProgress(kb) * 100)

  let doc = `# System Documentation\n\n`
  doc += `**Project:** ${projectName}\n`
  doc += `**Generated by:** Aluria — AI System Analyst\n`
  doc += `**Date:** ${date}\n`
  doc += `**Document Type:** Business Requirements Document (BRD) + Software Requirements Specification (SRS)\n`
  doc += `**Completion:** ${completionPct}% | **Depth Score:** ${depthScore}/100\n\n`
  doc += `---\n\n`

  // ── 1. Executive Summary ──────────────────────────────────────────────────
  doc += `## Executive Summary\n\n`

  doc += `### Problem\n\n`
  doc += kb.problem ? `${kb.problem}\n\n` : `*(Not yet defined)*\n\n`

  doc += `### Goal\n\n`
  if (kb.problem_why.length > 0) {
    kb.problem_why.forEach((w) => { doc += `- ${w}\n` })
    doc += '\n'
  } else {
    doc += `*(Not yet defined)*\n\n`
  }

  if (kb.affected_who.length > 0) {
    doc += `### Affected Stakeholders\n\n`
    kb.affected_who.forEach((s) => { doc += `- ${s}\n` })
    doc += '\n'
  }

  doc += `---\n\n`

  // ── 2. Actors & Roles ─────────────────────────────────────────────────────
  doc += `## Actors & Roles\n\n`
  if (kb.actors.length > 0) {
    kb.actors.forEach((actor) => {
      doc += `### ${actor.name}\n`
      doc += `- **Role:** ${actor.role || '(not defined)'}\n`
      doc += `- **Responsibility:** ${actor.responsibility || '(not defined)'}\n\n`
    })
  } else {
    doc += `*(Not yet defined)*\n\n`
  }
  doc += `---\n\n`

  // ── 3. Process Flow ───────────────────────────────────────────────────────
  doc += `## Process Flow\n\n`
  if (kb.process_flow.length > 0) {
    kb.process_flow.forEach((step, i) => {
      doc += `${i + 1}. ${step}\n`
    })
    doc += '\n'

    if (kb.decision_points.length > 0) {
      doc += `### Decision Points\n\n`
      kb.decision_points.forEach((d) => { doc += `- ${d}\n` })
      doc += '\n'
    }

    if (kb.edge_cases.length > 0) {
      doc += `### Edge Cases / Error Scenarios\n\n`
      kb.edge_cases.forEach((e) => { doc += `- ${e}\n` })
      doc += '\n'
    }

    doc += `### BPMN Diagram\n\n`
    doc += '```mermaid\n'
    doc += generateMermaid(kb)
    doc += '\n```\n\n'
  } else {
    doc += `*(Not yet defined)*\n\n`
  }
  doc += `---\n\n`

  // ── 4. Functional Requirements ────────────────────────────────────────────
  doc += `## Functional Requirements\n\n`
  if (kb.functional_requirements.length > 0) {
    kb.functional_requirements.forEach((req, i) => {
      doc += `- **FR-${i + 1}:** ${req}\n`
    })
    doc += '\n'
  } else {
    doc += `*(Not yet defined)*\n\n`
  }
  doc += `---\n\n`

  // ── 5. Business Rules ─────────────────────────────────────────────────────
  doc += `## Business Rules\n\n`
  if (kb.business_rules.length > 0) {
    kb.business_rules.forEach((rule, i) => {
      doc += `- **BR-${i + 1}:** ${rule}\n`
    })
    doc += '\n'
  } else {
    doc += `*(None defined)*\n\n`
  }
  doc += `---\n\n`

  // ── 6. System Specification (SRS) ─────────────────────────────────────────
  doc += `## System Specification (SRS)\n\n`

  doc += `### Roles → Permissions\n\n`
  if (kb.actors.length > 0) {
    doc += `| Role | Responsibility | System Access |\n`
    doc += `|------|---------------|---------------|\n`
    kb.actors.forEach((a) => {
      doc += `| ${a.name} | ${a.role || '—'} | ${a.responsibility || '—'} |\n`
    })
    doc += '\n'
  } else {
    doc += `*(No actors defined)*\n\n`
  }

  doc += `### Flow → System Behavior\n\n`
  if (kb.process_flow.length > 0) {
    kb.process_flow.forEach((step, i) => {
      doc += `${i + 1}. ${step}\n`
    })
    doc += '\n'
  } else {
    doc += `*(No process defined)*\n\n`
  }

  doc += `### Functional → Modules\n\n`
  if (kb.functional_requirements.length > 0) {
    doc += `| Module ID | Description | Priority |\n`
    doc += `|-----------|-------------|----------|\n`
    kb.functional_requirements.forEach((req, i) => {
      doc += `| FR-${i + 1} | ${req} | High |\n`
    })
    doc += '\n'
  } else {
    doc += `*(No requirements defined)*\n\n`
  }

  doc += `### Non-Functional Requirements\n\n`
  doc += `| Category | Requirement |\n`
  doc += `|----------|-------------|\n`
  doc += `| Performance | System should respond within 2 seconds |\n`
  doc += `| Security | All user data must be encrypted at rest and in transit |\n`
  doc += `| Availability | 99.9% uptime target |\n`
  doc += `| Scalability | Must support concurrent users without degradation |\n\n`

  doc += `---\n\n`

  // ── Metadata ──────────────────────────────────────────────────────────────
  doc += `## Analysis Metadata\n\n`
  doc += `| Metric | Value |\n`
  doc += `|--------|-------|\n`
  doc += `| Completion Score | ${completionPct}% |\n`
  doc += `| Depth Score | ${depthScore}/100 |\n`
  doc += `| Total Actors | ${kb.actors.length} |\n`
  doc += `| Total Process Steps | ${kb.process_flow.length} |\n`
  doc += `| Total Functional Requirements | ${kb.functional_requirements.length} |\n`
  doc += `| Total Business Rules | ${kb.business_rules.length} |\n\n`

  doc += `---\n\n`
  doc += `*Generated by Aluria — Deterministic AI System Analyst*`

  return doc
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function escapeMermaid(text: string): string {
  return text.replace(/"/g, "'").replace(/\[/g, '(').replace(/\]/g, ')')
}

// ─── V2 Diagram Generators ────────────────────────────────────────────────────

/**
 * Generate a BPMN-style text flow + Mermaid flowchart TD from KB V2 process_flow.
 * Decision points are inferred from business_rules containing IF/WHEN/UNLESS.
 * Returns empty string if process_flow is empty.
 */
export function generateBPMNFromV2(kb: KnowledgeBaseV2): string {
  kb = safe(kb)
  if (kb.process_flow.length === 0) return ''

  // Detect decision rules
  const decisionRules = kb.business_rules.filter((r) =>
    /\b(IF|WHEN|UNLESS|IF NOT)\b/i.test(r.condition)
  )

  // Text-based BPMN flow
  let textFlow = '▶ Start'
  for (const step of kb.process_flow) {
    const actor = step.actor ? `${step.actor}: ` : ''
    textFlow += ` → [${actor}${step.action}]`
  }
  textFlow += ' → ■ End'

  // Mermaid flowchart TD
  let mermaid = 'flowchart TD\n'
  mermaid += '  Start([▶ Start])\n'

  for (let i = 0; i < kb.process_flow.length; i++) {
    const step = kb.process_flow[i]
    const actor = step.actor ? `${step.actor}: ` : ''
    const label = `${actor}${step.action}`.slice(0, 50)
    mermaid += `  Step${i + 1}["${escapeMermaid(label)}"]\n`
  }

  // Add decision gateways from business rules
  for (let i = 0; i < decisionRules.length; i++) {
    const label = decisionRules[i].condition.slice(0, 40)
    mermaid += `  Dec${i + 1}{"${escapeMermaid(label)}"}\n`
  }

  mermaid += '  End([■ End])\n'

  // Connect steps
  mermaid += '  Start --> Step1\n'
  for (let i = 0; i < kb.process_flow.length - 1; i++) {
    mermaid += `  Step${i + 1} --> Step${i + 2}\n`
  }
  mermaid += `  Step${kb.process_flow.length} --> End\n`

  // Attach decision gateways to relevant steps
  for (let i = 0; i < decisionRules.length; i++) {
    const stepIdx = Math.min(i + 1, kb.process_flow.length)
    mermaid += `  Step${stepIdx} -.->|decision| Dec${i + 1}\n`
  }

  return `${textFlow}\n\n\`\`\`mermaid\n${mermaid}\`\`\``
}

/**
 * Generate a Mermaid sequenceDiagram from use_cases.normal.
 * Returns empty string if use_cases.normal is empty.
 */
export function generateUMLSequence(kb: KnowledgeBaseV2): string {
  kb = safe(kb)
  if (kb.use_cases.normal.length === 0) return ''

  let diagram = 'sequenceDiagram\n'
  diagram += '  participant User\n'
  diagram += '  participant System\n'
  diagram += '  participant Database\n'

  for (const uc of kb.use_cases.normal) {
    const actor = uc.actor || 'User'
    diagram += `\n  Note over ${actor},System: ${escapeMermaid(uc.title)}\n`
    for (const step of uc.steps) {
      diagram += `  ${escapeMermaid(actor)}->>System: ${escapeMermaid(step)}\n`
      diagram += `  System-->>Database: persist\n`
      diagram += `  Database-->>System: ok\n`
      diagram += `  System-->>${escapeMermaid(actor)}: response\n`
    }
  }

  return '```mermaid\n' + diagram + '```'
}

/**
 * Generate a Mermaid erDiagram from data_model.entities and relationships.
 * Returns empty string if data_model.entities is empty.
 */
export function generateERD(kb: KnowledgeBaseV2): string {
  kb = safe(kb)
  if (kb.data_model.entities.length === 0) return ''

  let diagram = 'erDiagram\n'

  for (const entity of kb.data_model.entities) {
    diagram += `  ${escapeMermaid(entity.name)} {\n`
    for (const field of entity.fields) {
      diagram += `    ${field.type || 'string'} ${escapeMermaid(field.name)}\n`
    }
    diagram += '  }\n'
  }

  const cardinalityMap: Record<string, string> = {
    '1:1': '||--||',
    '1:N': '||--o{',
    'N:N': '}o--o{',
  }

  for (const rel of kb.data_model.relationships) {
    const notation = cardinalityMap[rel.cardinality] ?? '||--o{'
    diagram += `  ${escapeMermaid(rel.from)} ${notation} ${escapeMermaid(rel.to)} : ""\n`
  }

  return '```mermaid\n' + diagram + '```'
}

/**
 * Generate the full 19-section PSB document as a Markdown string.
 * Pure function — no side effects.
 */
export function generatePSB(kb: KnowledgeBaseV2, projectName: string): string {
  kb = safe(kb)
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })
  const depthScore = calculateDepthV2(kb)
  const completionPct = Math.round(computeProgressV2(kb) * 100)

  const NA = '*(Not yet defined)*'

  let doc = `# Product System Blueprint (PSB)\n\n`
  doc += `**Project:** ${projectName}\n`
  doc += `**Generated by:** Aluria — AI System Architect Platform\n`
  doc += `**Date:** ${date}\n`
  doc += `**Document Type:** Product System Blueprint (PSB)\n`
  doc += `**Completion:** ${completionPct}% | **Depth Score:** ${depthScore}/100\n\n`
  doc += `---\n\n`

  // 1. Executive Summary
  doc += `## 1. Executive Summary\n\n`
  if (kb.business.problem) {
    doc += `${kb.business.problem}\n\n`
  } else {
    doc += `${NA}\n\n`
  }

  // 2. Problem Statement
  doc += `## 2. Problem Statement\n\n`
  doc += kb.business.problem ? `${kb.business.problem}\n\n` : `${NA}\n\n`

  // 3. Business Objectives
  doc += `## 3. Business Objectives\n\n`
  if (kb.business.objectives.length > 0) {
    kb.business.objectives.forEach((o) => { doc += `- ${o}\n` })
    doc += '\n'
  } else {
    doc += `${NA}\n\n`
  }

  // 4. Stakeholders
  doc += `## 4. Stakeholders\n\n`
  if (kb.business.stakeholders.length > 0) {
    kb.business.stakeholders.forEach((s) => {
      doc += `### ${s.name}\n`
      if (s.goals.length > 0) {
        doc += `**Goals:** ${s.goals.join(', ')}\n`
      }
      if (s.pain_points.length > 0) {
        doc += `**Pain Points:** ${s.pain_points.join(', ')}\n`
      }
      doc += '\n'
    })
  } else if (kb.actors.length > 0) {
    kb.actors.forEach((a) => {
      doc += `### ${a.name}\n`
      doc += `${a.description || '(no description)'}\n\n`
    })
  } else {
    doc += `${NA}\n\n`
  }

  // 5. AS-IS Process
  doc += `## 5. AS-IS Process\n\n`
  if (kb.process_flow.length > 0) {
    kb.process_flow.forEach((step, i) => {
      doc += `${i + 1}. **${step.actor || 'System'}**: ${step.action}\n`
    })
    doc += '\n'
  } else {
    doc += `${NA}\n\n`
  }

  // 6. TO-BE Process
  doc += `## 6. TO-BE Process\n\n`
  if (kb.process_flow.length > 0) {
    doc += `The improved process flow with system automation:\n\n`
    kb.process_flow.forEach((step, i) => {
      const systemNote = step.system ? ` *(System: ${step.system})*` : ''
      doc += `${i + 1}. **${step.actor || 'System'}**: ${step.action}${systemNote}\n`
    })
    doc += '\n'
  } else {
    doc += `${NA}\n\n`
  }

  // 7. Key Improvements
  doc += `## 7. Key Improvements\n\n`
  if (kb.business.objectives.length > 0) {
    kb.business.objectives.forEach((o) => { doc += `- ${o}\n` })
    doc += '\n'
  } else {
    doc += `${NA}\n\n`
  }

  // 8. Use Cases
  doc += `## 8. Use Cases\n\n`
  if (kb.use_cases.normal.length > 0 || kb.use_cases.edge.length > 0) {
    if (kb.use_cases.normal.length > 0) {
      doc += `### Normal Use Cases\n\n`
      kb.use_cases.normal.forEach((uc) => {
        doc += `#### ${uc.title}\n`
        doc += `**Actor:** ${uc.actor}\n\n`
        if (uc.steps.length > 0) {
          uc.steps.forEach((s, i) => { doc += `${i + 1}. ${s}\n` })
          doc += '\n'
        }
      })
      // Embed UML sequence diagram
      const uml = generateUMLSequence(kb)
      if (uml) {
        doc += `### Sequence Diagram\n\n${uml}\n\n`
      }
    }
    if (kb.use_cases.edge.length > 0) {
      doc += `### Edge Cases\n\n`
      kb.use_cases.edge.forEach((uc) => {
        doc += `#### ${uc.title}\n`
        doc += `**Condition:** ${uc.condition}\n`
        doc += `**System Response:** ${uc.system_response || '(not defined)'}\n\n`
      })
    }
  } else {
    doc += `${NA}\n\n`
  }

  // 9. Process Flow
  doc += `## 9. Process Flow\n\n`
  if (kb.process_flow.length > 0) {
    kb.process_flow.forEach((step, i) => {
      doc += `${i + 1}. **[${step.actor || 'System'}]** ${step.action}\n`
    })
    doc += '\n'
    // Embed BPMN diagram
    const bpmn = generateBPMNFromV2(kb)
    if (bpmn) {
      doc += `### Process Diagram\n\n${bpmn}\n\n`
    }
  } else {
    doc += `${NA}\n\n`
  }

  // 10. Functional Requirements
  doc += `## 10. Functional Requirements\n\n`
  if (kb.functional_requirements.length > 0) {
    kb.functional_requirements.forEach((req) => {
      doc += `### ${req.id}: ${req.name}\n`
      doc += `${req.description}\n`
      if (req.acceptance_criteria.length > 0) {
        doc += `\n**Acceptance Criteria:**\n`
        req.acceptance_criteria.forEach((ac) => { doc += `- ${ac}\n` })
      }
      doc += '\n'
    })
  } else {
    doc += `${NA}\n\n`
  }

  // 11. Business Rules
  doc += `## 11. Business Rules\n\n`
  if (kb.business_rules.length > 0) {
    kb.business_rules.forEach((rule) => {
      doc += `- **${rule.id}:** IF ${rule.condition} THEN ${rule.action || '(action not defined)'}\n`
    })
    doc += '\n'
  } else {
    doc += `${NA}\n\n`
  }

  // 12. Data Model (ERD)
  doc += `## 12. Data Model (ERD)\n\n`
  if (kb.data_model.entities.length > 0) {
    kb.data_model.entities.forEach((entity) => {
      doc += `### ${entity.name}\n`
      if (entity.fields.length > 0) {
        doc += `| Field | Type |\n|-------|------|\n`
        entity.fields.forEach((f) => { doc += `| ${f.name} | ${f.type} |\n` })
        doc += '\n'
      }
    })
    // Embed ERD
    const erd = generateERD(kb)
    if (erd) {
      doc += `### Entity Relationship Diagram\n\n${erd}\n\n`
    }
  } else {
    doc += `${NA}\n\n`
  }

  // 13. System Architecture
  doc += `## 13. System Architecture\n\n`
  const arch = kb.system_design.architecture
  if (arch.frontend || arch.backend || arch.database || arch.ai_layer) {
    doc += `| Layer | Technology |\n|-------|------------|\n`
    if (arch.frontend) doc += `| Frontend | ${arch.frontend} |\n`
    if (arch.backend) doc += `| Backend | ${arch.backend} |\n`
    if (arch.database) doc += `| Database | ${arch.database} |\n`
    if (arch.ai_layer) doc += `| AI Layer | ${arch.ai_layer} |\n`
    doc += '\n'
  } else {
    doc += `${NA}\n\n`
  }

  // 14. API Design
  doc += `## 14. API Design\n\n`
  if (kb.system_design.api_endpoints.length > 0) {
    doc += `| Method | Path | Description |\n|--------|------|-------------|\n`
    kb.system_design.api_endpoints.forEach((ep) => {
      doc += `| ${ep.method} | ${ep.path} | ${ep.description} |\n`
    })
    doc += '\n'
  } else {
    doc += `${NA}\n\n`
  }

  // 15. UI/UX Guidelines
  doc += `## 15. UI/UX Guidelines\n\n`
  if (kb.ux.user_flow.length > 0 || kb.ux.screens.length > 0) {
    if (kb.ux.user_flow.length > 0) {
      doc += `### User Flow\n\n`
      kb.ux.user_flow.forEach((f) => { doc += `- ${f}\n` })
      doc += '\n'
    }
    if (kb.ux.screens.length > 0) {
      doc += `### Screens\n\n`
      kb.ux.screens.forEach((s) => { doc += `- ${s}\n` })
      doc += '\n'
    }
  } else {
    doc += `${NA}\n\n`
  }

  // 16. Security Considerations
  doc += `## 16. Security Considerations\n\n`
  const securityRules = kb.business_rules.filter((r) =>
    /\b(auth|permission|access|role|secure|encrypt|password|token|login|admin)\b/i.test(
      r.condition + ' ' + r.action
    )
  )
  if (securityRules.length > 0) {
    securityRules.forEach((r) => {
      doc += `- IF ${r.condition} THEN ${r.action}\n`
    })
    doc += '\n'
  } else {
    doc += `- All user data must be encrypted at rest and in transit\n`
    doc += `- Authentication required for all protected routes\n`
    doc += `- Role-based access control enforced at API layer\n\n`
  }

  // 17. Performance Requirements
  doc += `## 17. Performance Requirements\n\n`
  doc += `| Metric | Target |\n|--------|--------|\n`
  doc += `| API Response Time | < 2 seconds |\n`
  doc += `| Availability | 99.9% uptime |\n`
  doc += `| Concurrent Users | Scalable without degradation |\n\n`

  // 18. Risk Register (from business_rules with conditional logic)
  doc += `## 18. Risk Register\n\n`
  const riskRules = kb.business_rules.filter((r) =>
    /\b(IF|WHEN|UNLESS|IF NOT)\b/i.test(r.condition)
  )
  if (riskRules.length > 0) {
    doc += `| Risk | Condition | Mitigation |\n|------|-----------|------------|\n`
    riskRules.forEach((r) => {
      doc += `| ${r.id} | ${r.condition} | ${r.action || 'To be defined'} |\n`
    })
    doc += '\n'
  } else {
    doc += `${NA}\n\n`
  }

  // 19. Implementation Roadmap
  doc += `## 19. Implementation Roadmap\n\n`
  if (kb.functional_requirements.length > 0) {
    const total = kb.functional_requirements.length
    const third = Math.ceil(total / 3)
    const phase1 = kb.functional_requirements.slice(0, third)
    const phase2 = kb.functional_requirements.slice(third, third * 2)
    const phase3 = kb.functional_requirements.slice(third * 2)

    doc += `### Phase 1 — Core\n\n`
    phase1.forEach((r) => { doc += `- **${r.id}:** ${r.name}\n` })
    doc += '\n'

    if (phase2.length > 0) {
      doc += `### Phase 2 — Extended\n\n`
      phase2.forEach((r) => { doc += `- **${r.id}:** ${r.name}\n` })
      doc += '\n'
    }

    if (phase3.length > 0) {
      doc += `### Phase 3 — Advanced\n\n`
      phase3.forEach((r) => { doc += `- **${r.id}:** ${r.name}\n` })
      doc += '\n'
    }
  } else {
    doc += `${NA}\n\n`
  }

  doc += `---\n\n`
  doc += `*Generated by Aluria — AI System Architect Platform*`

  return doc
}
